---
- hosts: all
  become: true
  pre_tasks:
    - name: Setup ufw
      shell: apt-get update && apt-get install -y ufw
  roles:
    - role: nginxinc.nginx
  post_tasks:
    - name: Upload website files
      copy: src=../website/ dest=/usr/share/nginx/html/ mode=0644

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp