---
- name: Install Jenkins
  hosts: all
  become: true
  vars:
    ssh_use_pam: true
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    ansible_remote_tmp: /tmp/ansible
    jenkins_plugins: [ ansicolor ]

  roles:
    - geerlingguy.jenkins 
    - geerlingguy.ansible-role-packer
    - geerlingguy.ansible  